hpx::util::activate_counters
typedef std::vector<future<performance_counters::counter_value> > hpx::util::activate_counters::async_counter_values_type
typedef std::vector<performance_counters::counter_value> hpx::util::activate_counters::sync_counter_values_type
std::vector<std::string> hpx::util::activate_counters::names_
std::vector<naming::id_type> hpx::util::activate_counters::ids_
std::vector<std::string> hpx::util::activate_counters::uoms_
hpx::util::activate_counters::activate_counters(std::vector< std::string > const &names)
References start_counters.
hpx::util::activate_counters::~activate_counters()
References stop_counters.
void hpx::util::activate_counters::reset_counters(error_code &ec=throws)
References HPX_THROWS_IF, hpx::invalid_status, i, hpx::async, hpx::lcos::wait_all, f, hpx::throws, hpx::make_error_code.
std::vector< future< performance_counters::counter_value > > hpx::util::activate_counters::evaluate_counters(launch::async_policy, bool reset=false, error_code &ec=throws)
References HPX_THROWS_IF, hpx::invalid_status, i, hpx::async.
Referenced by evaluate_counters.
std::vector< performance_counters::counter_value > hpx::util::activate_counters::evaluate_counters(launch::sync_policy, bool reset=false, error_code &ec=throws)
References evaluate_counters, hpx::async, hpx::util::unwrap.
std::string hpx::util::activate_counters::name(std::size_t i) const
References i.
Referenced by find_counters, start_counters.
naming::id_type hpx::util::activate_counters::id(std::size_t i) const
References i.
std::string hpx::util::activate_counters::unit_of_measure(std::size_t i) const
References i.
void hpx::util::activate_counters::find_counters()
References hpx::components::detail::names, hpx::compute::swap, hpx::util::placeholders::_1, hpx::util::placeholders::_2, func, hpx::util::bind, find_counter, name, hpx::util::expand, hpx::performance_counters::discover_counter_type, hpx::performance_counters::discover_counters_full, HPX_ASSERT.
Referenced by start_counters.
bool hpx::util::activate_counters::find_counter(performance_counters::counter_info const &info, error_code &ec)
References hpx::performance_counters::get_counter, hpx::performance_counters::counter_info::fullname_, HPX_UNLIKELY, HPX_THROWS_IF, hpx::bad_parameter, hpx::error_code::get_message, hpx::performance_counters::counter_info::unit_of_measure_.
Referenced by find_counters.
void hpx::util::activate_counters::start_counters(error_code &ec=throws)
References name, hpx::performance_counters::ensure_counter_prefix, find_counters, i, hpx_optsweep.start, hpx::async, hpx::lcos::wait_all, f, hpx::throws, hpx::make_error_code.
Referenced by activate_counters.
void hpx::util::activate_counters::stop_counters(error_code &ec=throws)
References HPX_THROWS_IF, hpx::invalid_status, i, hpx::stop, hpx::async, hpx::lcos::wait_all, f, hpx::throws, hpx::make_error_code.
Referenced by ~activate_counters.