hpx::serialization::access
static void hpx::serialization::access::serialize(Archive &ar, T &t, unsigned)
Referenced by partition_data::size, hpx::serialization::base_object_type< Derived, Base, Enable >::serialize, hpx::parallel::execution::sequenced_task_policy_shim< Executor, Parameters >::parameters, hpx::parallel::execution::sequenced_policy_shim< Executor, Parameters >::parameters, hpx::parallel::execution::parallel_task_policy_shim< Executor, Parameters >::parameters, hpx::parallel::execution::parallel_policy_shim< Executor, Parameters >::parameters, small_object::operator().
static HPX_FORCEINLINE void hpx::serialization::access::save_base_object(Archive &ar, const T &t, unsigned)
Referenced by hpx::serialization::base_object_type< Derived, Base, std::true_type >::save.
static HPX_FORCEINLINE void hpx::serialization::access::load_base_object(Archive &ar, T &t, unsigned)
Referenced by hpx::serialization::base_object_type< Derived, Base, std::true_type >::load.
static HPX_FORCEINLINE std::string hpx::serialization::access::get_name(const T *t)