hpx::actions::detail::action_registry
typedef base_action*(* hpx::actions::detail::action_registry::ctor_t) (bool))(bool)
typedef std::unordered_map<std::string, ctor_t> hpx::actions::detail::action_registry::typename_to_ctor_t
typedef std::unordered_map<std::string, std::uint32_t> hpx::actions::detail::action_registry::typename_to_id_t
typedef std::vector<ctor_t> hpx::actions::detail::action_registry::cache_t
HPX_STATIC_CONSTEXPR std::uint32_t hpx::actions::detail::action_registry::invalid_id
Referenced by register_typename, try_get_id, get_id, hpx::agas::detail::assigned_id_sequence::load.
std::uint32_t hpx::actions::detail::action_registry::max_id_
Referenced by register_typename, fill_missing_typenames, hpx::agas::detail::assigned_id_sequence::load.
typename_to_ctor_t hpx::actions::detail::action_registry::typename_to_ctor_
Referenced by register_factory, register_typename, fill_missing_typenames, get_unassigned_typenames, collect_registered_typenames.
typename_to_id_t hpx::actions::detail::action_registry::typename_to_id_
Referenced by register_factory, register_typename, fill_missing_typenames, try_get_id, get_unassigned_typenames, collect_registered_typenames.
cache_t hpx::actions::detail::action_registry::cache_
Referenced by create, cache_id.
hpx::actions::detail::action_registry::HPX_NON_COPYABLE(action_registry)
hpx::actions::detail::action_registry::action_registry()
void hpx::actions::detail::action_registry::register_factory(std::string const &type_name, ctor_t ctor)
References HPX_ASSERT, typename_to_ctor_, typename_to_id_, cache_id.
Referenced by hpx::actions::detail::register_action< Action >::register_action.
void hpx::actions::detail::action_registry::register_typename(std::string const &type_name, std::uint32_t id)
References HPX_ASSERT, invalid_id, typename_to_id_, HPX_THROW_EXCEPTION, hpx::invalid_status, typename_to_ctor_, cache_id, max_id_.
Referenced by fill_missing_typenames, hpx::actions::detail::add_constant_entry< Id >::add_constant_entry, hpx::agas::detail::assigned_id_sequence::load, hpx::agas::detail::assigned_id_sequence::register_ids_on_worker_loc.
void hpx::actions::detail::action_registry::fill_missing_typenames()
References get_unassigned_typenames, register_typename, max_id_, typename_to_id_, typename_to_ctor_, cache_id, HPX_ASSERT.
Referenced by hpx::agas::detail::register_unassigned_typenames, hpx::agas::detail::assigned_id_sequence::register_ids_on_worker_loc.
std::uint32_t hpx::actions::detail::action_registry::try_get_id(std::string const &type_name) const
References typename_to_id_, invalid_id.
Referenced by get_id, hpx::agas::detail::assigned_id_sequence::load.
std::vector< std::string > hpx::actions::detail::action_registry::get_unassigned_typenames() const
References typename_to_ctor_, typename_to_id_.
Referenced by fill_missing_typenames, hpx::agas::detail::assigned_id_sequence::register_ids_on_worker_loc.
void hpx::actions::detail::action_registry::cache_id(std::uint32_t id, ctor_t ctor)
References cache_.
Referenced by register_factory, register_typename, fill_missing_typenames.
std::string hpx::actions::detail::action_registry::collect_registered_typenames()
References msg, typename_to_ctor_, typename_to_id_, to_string.
Referenced by get_id, create.
std::uint32_t hpx::actions::detail::action_registry::get_id(std::string const &type_name)
References instance, try_get_id, invalid_id, HPX_THROW_EXCEPTION, hpx::serialization_error, collect_registered_typenames.
Referenced by hpx::actions::detail::get_action_id_from_name.
base_action * hpx::actions::detail::action_registry::create(std::uint32_t id, bool, std::string const *name=nullptr)
References instance, cache_, msg, to_string, collect_registered_typenames, HPX_THROW_EXCEPTION, hpx::serialization_error.
Referenced by hpx::actions::detail::register_action< Action >::register_action.
action_registry & hpx::actions::detail::action_registry::instance()
Referenced by get_id, create, hpx::actions::detail::register_action< Action >::register_action, hpx::actions::detail::add_constant_entry< Id >::add_constant_entry, hpx::agas::detail::register_unassigned_typenames, hpx::agas::detail::assigned_id_sequence::load, hpx::agas::detail::assigned_id_sequence::register_ids_on_worker_loc.