hpx::test::server::action_move_semantics
std::size_t hpx::test::server::action_move_semantics::test_movable(movable_object const &obj)
References hpx::test::movable_object::get_count.
Referenced by return_test_non_movable.
std::size_t hpx::test::server::action_move_semantics::test_non_movable(non_movable_object const &obj)
References hpx::test::non_movable_object::get_count.
Referenced by return_test_non_movable.
movable_object hpx::test::server::action_move_semantics::return_test_movable()
Referenced by return_test_non_movable.
non_movable_object hpx::test::server::action_move_semantics::return_test_non_movable()
References HPX_DEFINE_COMPONENT_ACTION, test_movable, test_non_movable, HPX_DEFINE_COMPONENT_DIRECT_ACTION, return_test_movable, HPX_REGISTER_ACTION_DECLARATION.
hpx::test::server::action_move_semantics::HPX_DEFINE_COMPONENT_ACTION(action_move_semantics, test_movable, test_movable_action)
Referenced by return_test_non_movable.
hpx::test::server::action_move_semantics::HPX_DEFINE_COMPONENT_ACTION(action_move_semantics, test_non_movable, test_non_movable_action)
hpx::test::server::action_move_semantics::HPX_DEFINE_COMPONENT_DIRECT_ACTION(action_move_semantics, test_movable, test_movable_direct_action)
Referenced by return_test_non_movable.
hpx::test::server::action_move_semantics::HPX_DEFINE_COMPONENT_DIRECT_ACTION(action_move_semantics, test_non_movable, test_non_movable_direct_action)
hpx::test::server::action_move_semantics::HPX_DEFINE_COMPONENT_ACTION(action_move_semantics, return_test_movable, return_test_movable_action)
hpx::test::server::action_move_semantics::HPX_DEFINE_COMPONENT_ACTION(action_move_semantics, return_test_non_movable, return_test_non_movable_action)
hpx::test::server::action_move_semantics::HPX_DEFINE_COMPONENT_DIRECT_ACTION(action_move_semantics, return_test_movable, return_test_movable_direct_action)
hpx::test::server::action_move_semantics::HPX_DEFINE_COMPONENT_DIRECT_ACTION(action_move_semantics, return_test_non_movable, return_test_non_movable_direct_action)