hpx::traits::action_was_object_migrated
static std::pair<bool, components::pinned_ptr> hpx::traits::action_was_object_migrated< Action, Enable >::call(hpx::naming::gid_type const &id, naming::address::address_type lva)
Referenced by hpx::detail::apply_impl, hpx::detail::apply_cb_impl, hpx::lcos::packaged_action< Action, Result, true >::apply, hpx::lcos::packaged_action< Action, Result, true >::apply_cb, hpx::components::stubs::runtime_support::free_component_sync, hpx::actions::transfer_base_action< Action >::get_static_component_type.
static std::pair<bool, components::pinned_ptr> hpx::traits::action_was_object_migrated< Action, Enable >::call(hpx::naming::id_type const &id, naming::address::address_type lva)