examples::accumulator
typedef hpx::components::client_base< accumulator, server::accumulator > examples::accumulator::base_type
typedef server::accumulator::argument_type examples::accumulator::argument_type
examples::accumulator::accumulator()
Default construct an empty client side representation (not connected to any existing component).
examples::accumulator::accumulator(hpx::future< hpx::id_type > &&gid)
Create a client side representation for the existing server::accumulator instance with the given GID.
void examples::accumulator::reset(hpx::launch::apply_policy)
Reset the accumulator's value to 0.This function has fire-and-forget semantics. It will not wait for the action to be executed. Instead, it will return immediately after the action has has been dispatched.
References HPX_ASSERT, hpx::components::client_base< accumulator, server::accumulator >::get_id.
Referenced by hpx_main.
void examples::accumulator::reset(hpx::launch::sync_policy=hpx::launch::sync)
Reset the accumulator's value to 0.This function is fully synchronous.
References HPX_ASSERT, hpx::components::client_base< accumulator, server::accumulator >::get_id.
void examples::accumulator::add(hpx::launch::apply_policy, argument_type arg)
Add arg to the accumulator's value.This function has fire-and-forget semantics. It will not wait for the action to be executed. Instead, it will return immediately after the action has has been dispatched.
References HPX_ASSERT, hpx::components::client_base< accumulator, server::accumulator >::get_id.
Referenced by hpx_main.
void examples::accumulator::add(argument_type arg)
Add arg to the accumulator's value.This function is fully synchronous.
References HPX_ASSERT, hpx::components::client_base< accumulator, server::accumulator >::get_id.
hpx::future<argument_type> examples::accumulator::query(hpx::launch::async_policy)
Asynchronously query the current value of the accumulator.This function returns an hpx::lcos::future. When the value of this computation is needed, the get() method of the future should be called. If the value is available, get() will return immediately; otherwise, it will block until the value is ready.
References HPX_ASSERT, hpx::components::client_base< accumulator, server::accumulator >::get_id, hpx::async.
Referenced by hpx_main.
argument_type examples::accumulator::query(hpx::launch::sync_policy=hpx::launch::sync)
Query the current value of the accumulator.This function is fully synchronous.
References HPX_ASSERT, hpx::components::client_base< accumulator, server::accumulator >::get_id.