A
typedef int A< T >::result_type
int A< T >::val
int A< T >::m
int A< T >::a
Referenced by member_bind_test0, member_bind_test1, main, test_create_single_instance_non_copyable_arg, serialize, A< T >::~A, A< T >::serialize, T, a_factory, B< T >::get_a, load_construct_data, operator<<, intrusive_ptr_release, test_shared, test_intrusive, make_tuple_test, tie_test.
int A< T >::p
Referenced by test_void_promise, test_reference_promise, test_destroying_a_promise_stores_broken_promise, test_destroying_a_packaged_task_stores_broken_task, smart_ptr< T >::operator*, HPX_DEFINE_TAG_SPECIFIER.
int A< T >::a
T A< T >::t_
Referenced by A< T >::serialize, test, test_fp, test_boost_array, test_std_array, test_bool, A< T >::operator==, test_std_valarray.
int A< T >::i
Referenced by A< T >::test1, main, test, test_fp, test_boost_array, test_std_array, test_multi_array, test_plain_array, test_array_of_vectors, A< T >::serialize, test_bool, test_non_default_constructible, test_std_valarray, test_long_vector_serialization, tie_test, tuple_swap_test.
int A< T >::count
Referenced by intrusive_ptr_add_ref, intrusive_ptr_release, test_shared.
int A< T >::value_
Referenced by B< T >::print, B< T >::B, HPX_DEFINE_TAG_SPECIFIER.
constexpr A< T >::A(int i)
A< T >::A()
References hpx::cout, hpx::iostreams::flush.
Referenced by test_basic, main, A< T >::A, a_factory, test_delegate, test_intrusive, make_tuple_test.
virtual A< T >::~A()
References hpx::cout, hpx::iostreams::flush, A< T >::print.
virtual void A< T >::print() const =0
Referenced by A< T >::~A, A< T >::print_nonvirt.
void A< T >::print_nonvirt() const
References A< T >::print, A< T >::HPX_DEFINE_COMPONENT_ACTION, HPX_DEFINE_GET_COMPONENT_TYPE.
A< T >::HPX_DEFINE_COMPONENT_ACTION(A, print_nonvirt, print_action)
Referenced by A< T >::print_nonvirt, A< T >::test0_nonvirt, B< T >::test1, B< T >::test1_nonvirt, C< T >::test2, test_server::call.
A< T >::A()
References a_ctor.
virtual A< T >::~A()
References a_dtor, A< T >::test0.
virtual std::string A< T >::test0() const =0
Referenced by member_bind_test0, A< T >::~A, A< T >::test0_nonvirt.
std::string A< T >::test0_nonvirt() const
References A< T >::test0, A< T >::HPX_DEFINE_COMPONENT_ACTION, HPX_DEFINE_GET_COMPONENT_TYPE.
Referenced by A< T >::test0_nonvirt.
A< T >::HPX_DEFINE_COMPONENT_ACTION(A, test0_nonvirt, test0_action)
A< T >::A()
References a_ctor.
virtual A< T >::~A()
References a_dtor.
virtual std::string A< T >::test0() const
std::string A< T >::test0_nonvirt() const
References A< T >::test0, A< T >::HPX_DEFINE_COMPONENT_ACTION, A< T >::test0_nonvirt.
A< T >::HPX_DEFINE_COMPONENT_ACTION(A, test0_nonvirt, test0_action)
A< T >::A()
References a_ctor.
virtual A< T >::~A()
References a_dtor, A< T >::test0.
virtual std::string A< T >::test0() const =0
std::string A< T >::test0_nonvirt() const
References A< T >::test0, A< T >::HPX_DEFINE_COMPONENT_ACTION, A< T >::test0_nonvirt, HPX_DEFINE_GET_COMPONENT_TYPE.
A< T >::HPX_DEFINE_COMPONENT_ACTION(A, test0_nonvirt, test0_action)
A< T >::A()
References a_ctor.
virtual A< T >::~A()
References a_dtor, A< T >::test0.
virtual std::string A< T >::test0() const =0
std::string A< T >::test0_nonvirt() const
References A< T >::test0, A< T >::HPX_DEFINE_COMPONENT_ACTION, A< T >::test0_nonvirt, HPX_DEFINE_GET_COMPONENT_TYPE.
A< T >::HPX_DEFINE_COMPONENT_ACTION(A, test0_nonvirt, test0_action)
A< T >::A()
References a_ctor.
virtual A< T >::~A()
References a_dtor.
virtual std::string A< T >::test0() const
std::string A< T >::test0_nonvirt() const
References A< T >::test0, A< T >::HPX_DEFINE_COMPONENT_ACTION, A< T >::test0_nonvirt.
A< T >::HPX_DEFINE_COMPONENT_ACTION(A, test0_nonvirt, test0_action)
A< T >::A()=default
A< T >::A(A const &)=delete
A& A< T >::operator=(A const &)=delete
A< T >::A(int a=8)
virtual A< T >::~A()
A< T >::A()
virtual A< T >::~A()
References A< T >::a.
void A< T >::serialize(Archive &ar, unsigned)
References A< T >::a, A< T >::HPX_SERIALIZATION_POLYMORPHIC.
Referenced by c_factory, e_factory, T.
A< T >::HPX_SERIALIZATION_POLYMORPHIC(A)
Referenced by A< T >::serialize.
A< T >::A()
virtual A< T >::~A()
References A< T >::a.
void A< T >::serialize(Archive &ar, unsigned)
References A< T >::a, A< T >::HPX_SERIALIZATION_POLYMORPHIC.
A< T >::HPX_SERIALIZATION_POLYMORPHIC(A)
A< T >::A(int a)
References A< T >::A.
A< T >::A()=default
virtual A< T >::~A()
References A< T >::foo, HPX_TRAITS_NONINTRUSIVE_POLYMORPHIC_TEMPLATE.
virtual void A< T >::foo() const =0
Referenced by A< T >::~A, A< T >::A, D::~D, foo< T >::operator==, construction_test, mutate_test, tie_test.
A< T >::A(int a)
References A< T >::A, A< T >::foo.
A< T >::A()=default
virtual void A< T >::foo() const =0
void A< T >::serialize(Ar &ar, unsigned)
References A< T >::a, hpx::iostreams::endl, A< T >::HPX_SERIALIZATION_POLYMORPHIC_ABSTRACT.
A< T >::HPX_SERIALIZATION_POLYMORPHIC_ABSTRACT(A)
Referenced by B< T >::serialize, A< T >::serialize.
A< T >::A(int a=1)
virtual A< T >::~A()
References A< T >::foo.
virtual const char* A< T >::foo()=0
void A< T >::serialize(Archive &ar, unsigned)
References A< T >::a, A< T >::HPX_SERIALIZATION_POLYMORPHIC_ABSTRACT.
A< T >::HPX_SERIALIZATION_POLYMORPHIC_ABSTRACT(A)
A< T >::A(int a=1)
virtual A< T >::~A()
References A< T >::foo, HPX_TRAITS_NONINTRUSIVE_POLYMORPHIC.
virtual const char* A< T >::foo()=0
A< T >::A()
A< T >::A(T t)
A& A< T >::operator=(T t)
void A< T >::serialize(Archive &ar, unsigned)
References A< T >::t_.
A< T >::A()
A< T >::A(T t)
A& A< T >::operator=(T t)
void A< T >::serialize(Archive &ar, unsigned)
References A< T >::t_, A< T >::operator<<, A< T >::i.
A< T >::A()
A< T >::A(T t)
A& A< T >::operator=(T t)
void A< T >::serialize(Archive &ar, unsigned)
References A< T >::t_.
A< T >::A(int a)
virtual A< T >::~A()
References A< T >::a.
A< T >::A()
A< T >::A(T t)
A& A< T >::operator=(T t)
void A< T >::serialize(Archive &ar, unsigned)
References A< T >::t_.
A< T >::A()
A< T >::A(T t)
A& A< T >::operator=(T t)
void A< T >::serialize(Archive &ar, unsigned)
References A< T >::t_, A< T >::a.
A< T >::A()
A< T >::A(T t)
A& A< T >::operator=(T t)
bool A< T >::operator==(const A &a) const
References A< T >::t_.
void A< T >::serialize(Archive &ar, unsigned)
References A< T >::t_.
A< T >::A()
void A< T >::serialize(Archive &ar, unsigned)
References A< T >::i.
A< T >::A()
A< T >::A(T t)
A& A< T >::operator=(T t)
bool A< T >::operator==(const A &a) const
References A< T >::t_.
void A< T >::serialize(Archive &ar, unsigned)
References A< T >::t_.
A< T >::A()
A< T >::A(T t)
A& A< T >::operator=(T t)
void A< T >::serialize(Archive &ar, unsigned)
References A< T >::t_.
A< T >::A()
A< T >::A(T t)
A& A< T >::operator=(T t)
void A< T >::serialize(Archive &ar, unsigned)
References A< T >::t_.
A< T >::A()
A< T >::A(T t)
A& A< T >::operator=(T t)
void A< T >::serialize(Archive &ar, unsigned)
References A< T >::t_, A< T >::a.
int A< T >::test0()
int A< T >::test1(int i)
References A< T >::i.
Referenced by member_bind_test1, B< T >::test1, B< T >::test1_nonvirt, B< T >::test0.
A< T >::A(int val=0)
bool operator==(A a, A b)
std::ostream& operator<<(std::ostream &os, A a)
Referenced by A< T >::serialize.